/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef CRYSTALSERVER_PRIVATE_H
#define CRYSTALSERVER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	0
#define COMPANY_NAME	"OtLand.net"
#define FILE_VERSION	"1.0"
#define FILE_DESCRIPTION	"Crystal Server"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Crystal Server.exe"
#define PRODUCT_NAME	"Crystal Server"
#define PRODUCT_VERSION	"1.0"

#endif /*CRYSTALSERVER_PRIVATE_H*/
